# Movie Reviews and Bag-of-Words Modelling

🎯 The goal of this challenge is to play with the ***Bag-of-words*** modelling of texts.

✍️ In the following dataset, we have $2000$ reviews classified either as _"positive"_ or _"negative"_.

In [1]:
import pandas as pd

data = pd.read_csv("https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/10-Natural-Language-Processing/movie_reviews.csv")
data.head()

  target                                            reviews
0    neg  plot : two teen couples go to a church party ,...
1    neg  the happy bastard's quick movie review \ndamn ...
2    neg  it is movies like these that make a jaded movi...
3    neg   " quest for camelot " is warner bros . ' firs...
4    neg  synopsis : a mentally unstable man undergoing ...

In [2]:
data.shape

(2000, 2)

## 1. Preprocessing

❓ **Question (Cleaning Text)** ❓

- Write a function `preprocessing` that will clean a sentence and apply it to all our reviews. It should:
    - remove whitespace
    - lowercase characters
    - remove numbers
    - remove punctuation
    - tokenize
    - lemmatize
- You can store the cleaned reviews into a column called `clean_reviews`.
- Do not remove stopwords in this challenge, we will explain why in the section `3. N-gram modelling`

In [4]:
import string
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer

def preprocessing(sentence):
    sentence = sentence.strip()
    sentence = sentence.lower()
    sentence = ''.join(char for char in sentence if not char.isdigit())
    sentence = ''.join(char for char in sentence if char not in string.punctuation)
    tokens = word_tokenize(sentence)
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    clean_sentence = ' '.join(lemmatized_tokens)
    return clean_sentence

In [6]:
# Clean reviews
data["clean_reviews"] = data["reviews"].apply(preprocessing)

❓ **Question (LabelEncoding)**❓

LabelEncode your target and store it into a column called `"target_encoded"`

In [7]:
# YOUR CODE HERE
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

data['target_encoded'] = label_encoder.fit_transform(data['target'])

In [11]:
# Quick check
data.tail(20)

,target,reviews,clean_reviews,target_encoded
1980,pos,"in this good natured , pleasent and easy going...",in this good natured pleasent and easy going c...,1
1981,pos,""" no man is an island , "" one character quote...",no man is an island one character quote john d...,1
1982,pos,i rented this movie with very high hopes . \nt...,i rented this movie with very high hope this m...,1
1983,pos,few films in 1999 have divided the critical co...,few film in have divided the critical consensu...,1
1984,pos,"now that "" boogie nights "" has made disco resp...",now that boogie night ha made disco respectabl...,1
1985,pos,this has been an extraordinary year for austra...,this ha been an extraordinary year for austral...,1
1986,pos,i think the first thing this reviewer should m...,i think the first thing this reviewer should m...,1
1987,pos,trees lounge is the directoral debut from one ...,tree lounge is the directoral debut from one o...,1
1988,pos,i wish i could say that there is something mor...,i wish i could say that there is something mor...,1
1989,pos,"lisa cholodenko's "" high art , "" is an intelli...",lisa cholodenkos high art is an intelligent qu...,1
1990,pos,the relaxed dude rides a roller coaster \nthe ...,the relaxed dude ride a roller coaster the big...,1
1991,pos,i don't box with kid gloves . \ni don't play n...,i dont box with kid glove i dont play nice im ...,1
1992,pos,"here is a film that is so unexpected , so scar...",here is a film that is so unexpected so scary ...,1
1993,pos,plot : this movie takes place over one day . \...,plot this movie take place over one day it a r...,1
1994,pos,"a thriller set in modern day seattle , that ma...",a thriller set in modern day seattle that mark...,1
1995,pos,wow ! what a movie . \nit's everything a movie...,wow what a movie it everything a movie can be ...,1
1996,pos,"richard gere can be a commanding actor , but h...",richard gere can be a commanding actor but he ...,1
1997,pos,"glory--starring matthew broderick , denzel was...",glorystarring matthew broderick denzel washing...,1
1998,pos,steven spielberg's second epic film on world w...,steven spielberg second epic film on world war...,1
1999,pos,"truman ( "" true-man "" ) burbank is the perfect...",truman trueman burbank is the perfect name for...,1

## 2. Bag-of-Words Modelling

❓ **Question (NaiveBayes with unigrams)** ❓

Using `cross_validate`, score a Multinomial Naive Bayes model trained on a Bag-of-Words representation of the texts.

In [ ]:
# YOUR CODE HERE
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_validate

vectorizer = CountVectorizer()
naivebayes = MultinomialNB()

X_bow = vectorizer.fit_transform(data['clean_reviews'])

cv_nb = cross_validate(
    naivebayes,
    X_bow,
    data['target_encoded'],
    scoring = 'accuracy'

)

## 3. N-gram Modelling

👀 Remember that we asked you not to remove stopwords. Why? 

👉 We will train the Naive Bayes model with bigrams. Hence, in sentence like "I do not like coriander", it is important to scan the bigram "do not" to detect negativity in this sentence for example.

❓ **Question (NaiveBayes with bigrams)** ❓

Using `cross_validate`, score a Multinomial Naive Bayes model trained on a 2-gram Bag-of-Words representation of the texts.

In [13]:
vectorizer = CountVectorizer(ngram_range = (2,2))
naivebayes = MultinomialNB()

X_bow = vectorizer.fit_transform(data.clean_reviews)

cv_nb = cross_validate(
    naivebayes,
    X_bow,
    data.target_encoded,
    scoring = "accuracy"
)

round(cv_nb['test_score'].mean(),2)

0.84

🏁 Congratulations! Now, you know how to train a Naive Bayes model on vectorized texts.

💾 Don't forget to `git add/commit/push` your notebook...

🚀 ... and move on to the next challenge!